/**
* @author Ruan Alves
* Função: Inserindo Cobranças Complementos para Cobranças que não possuem essa tabela
*/
INSERT INTO COBRANCA_COMPLEMENTOS (DTULTALTERACAO, VLMINIMOVENDA, CODFUNCALT, CODCOBRANCA)
(SELECT NULL,0,NULL, CODCOBRANCA FROM COBRANCA WHERE CODCOBRANCA NOT IN (SELECT CODCOBRANCA FROM COBRANCA_COMPLEMENTOS))