/**
* @author Ruan Alves
* Função: Inserindo Empresa Complementos para Empresa que não possuem essa tabela
*/
INSERT INTO PARAMETROFV (CODVEND, VALORMINIMOVENDA, QTDEDIASATUALIZACAO, TIPOVENDAPADRAO, NOME)
(SELECT CODIGO,0, 10, 'SAIDA_TELEMARKETING', NOME FROM VENDEDOR WHERE CODIGO NOT IN (SELECT CODVEND FROM PARAMETROFV))
