/**
* @author Ruan Alves
* Função: Inserindo Vendedor Complementos para Vendedor que não possuem essa tabela
*/
INSERT INTO VENDEDOR_COMPLEMENTOS (ATIVO, CODVENDEDOR, PERMITEDESCSEMSALDOFLEXIVEL, USAFLEXIVEL, VLLIMCREDFLEX, VLSALDOFLEX)
(SELECT 1, CODIGO, 0, 0, 0, 0 FROM VENDEDOR WHERE CODIGO NOT IN (SELECT CODIGO FROM VENDEDOR_COMPLEMENTOS))