--REMOVE CARACTERES ESPECIAIS (ACENTOS, CEDILHA, ETC) DO CAMPO VARCHAR:
UPDATE PRODUTO SET NOME= NOME COLLATE sql_latin1_general_cp1251_ci_as

--NESTE EXEMPLO, ATUALIZA O CAMPO 'NOME' DA TABELA 'PESSOA'