/**
* @author Ruan Alves
* Função: Recalcular o Preco Mínimo de acordo com o Percentual de Desconto
*/
UPDATE PRECOTABELA SET 
PRECOMINIMO = ROUND(((PRECOCONSUMIDOR) - ((PRECOCONSUMIDOR) * ((PERDESCONTO)/100))),2), DTULTALTERACAO = GETDATE() 
	WHERE PERDESCONTO IS NOT NULL 
	AND PRECOCONSUMIDOR IS NOT NULL
	AND ISNULL(PRECOCONSUMIDOR, 0) > 0
	AND ISNULL(PERDESCONTO, 0) > 0
GO
UPDATE PRECOREGIAO SET 
PRECOMINIMO = ROUND(((PRECOCONSUMIDOR) - ((PRECOCONSUMIDOR) * ((PERDESCONTO)/100))),2), DTULTALTERACAO = GETDATE() 
	WHERE PERDESCONTO IS NOT NULL 
	AND PRECOCONSUMIDOR IS NOT NULL
	AND ISNULL(PRECOCONSUMIDOR, 0) > 0
	AND ISNULL(PERDESCONTO, 0) > 0