/**
* @author Ruan Alves
* Função: Verificar nas tabelas CONTASARECEBER/CONTASAPAGAR campos NULL
*/
SELECT NUMLANCAMENTO, NUMNOTA, DTVENCIMENTO, DTLANCAMENTO, VALOR, CODCOBRANCA, DTVENCORIGINAL, VLJURO, VLDESCONTO
	FROM CONTASARECEBER WHERE DTVENCIMENTO IS NULL OR DTLANCAMENTO IS NULL OR VALOR IS NULL
OR CODCOBRANCA IS NULL OR DTVENCORIGINAL IS NULL OR VLJURO IS NULL OR VLDESCONTO IS NULL
GO
SELECT NUMLANCAMENTO, NUMNOTA, DTVENCIMENTO, DTLANCAMENTO, VALOR, CODCOBRANCA, DTVENCORIGINAL, VLJURO, VLDESCONTO
	FROM CONTASAPAGAR WHERE DTVENCIMENTO IS NULL OR DTLANCAMENTO IS NULL OR VALOR IS NULL
OR CODCOBRANCA IS NULL OR DTVENCORIGINAL IS NULL OR VLJURO IS NULL OR VLDESCONTO IS NULL